defaults:
  - base_detector.yaml

optimizer:
  _target_: torch.optim.SGD
  lr: 0.01
  momentum: 0.9

detector:
  _target_: src.models.detectors.FasterRCNN
  backbone:
    _target_: src.models.backbones.resnet.resnet_backbone
    layer: 50
    fixed_blocks: 2
  rpn:
    _target_: src.models.detectors.faster_rcnn.modules.RPNLayer
    in_channels: 1024
    feat_channels: 1024
    feat_stride: 16
    proposal_layer:
      _target_: src.models.detectors.faster_rcnn.modules.ProposalLayer
      train_pre_nms_topN: 12000
      train_post_nms_topN: 2000
      test_pre_nms_topN: 6000
      test_post_nms_topN: 300
      nms_thresh: 0.7
      min_box_size: 16
    anchor_generator:
      _target_: src.models.detectors.faster_rcnn.modules.AnchorGenerator
      scales: [8, 16, 32]
      aspect_ratios: [0.5, 1, 2]
      feat_stride: 16
    anchor_target:
      _target_: src.models.detectors.faster_rcnn.modules.AnchorTargetGenerator
      batch_size: 256
      allowed_border: 0
      clobber_positives: False
      positive_overlap: 0.7
      negative_overlap: 0.3
      fg_fraction: 0.5
  rcnn:
    _target_: src.models.detectors.faster_rcnn.modules.RCNN
    roi_size: 7
    num_channels: 1024
    num_classes: 21
    spatial_scale: 0.0625
    proposal_target:
      _target_: src.models.detectors.faster_rcnn.modules.ProposalTargetGenerator
      _partial_: True
      batch_size: 128
      use_gt: True
      fg_fraction: 0.25
      fg_thresh: 0.5
      bg_thresh_high: 0.5
      bg_thresh_low: 0.1
      bbox_normalize_means: [0, 0, 0, 0]
      bbox_normalize_stds: [0.1, 0.1, 0.2, 0.2]
