defaults:
  - base_detector.yaml

optimizer:
  _target_: torch.optim.SGD
  lr: 0.01
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0001

detector:
  _target_: src.models.detectors.FasterRCNN
  img_normalize_means: [123.675, 116.28, 103.53]
  img_normalize_stds: [58.395, 57.12, 57.375]
  backbone:
    _target_: src.models.backbones.ResnetBackbone
    depth: 50
    pretrained: True
    num_stages: 3
    frozen_stages: 1
  rpn_head:
    _target_: src.models.heads.RPNHead
    in_channels: 1024
    feat_channels: 512
    anchor_generator:
      _target_: src.models.generators.AnchorGenerator
      scales: [2, 4, 8, 16, 32]
      ratios: [0.5, 1, 2]
      stride: 16
    rpn_target_generator:
      _target_: src.models.generators.RPNTargetGenerator
      num_samples: 256
      fg_fraction: 0.5
      positive_iou_thr: 0.7
      negative_iou_thr: 0.3
      allowed_border: 4
    train_nms_cfg:
      nms_pre: 12000
      nms_post: 2000
      nms_thr: 0.7
      min_bbox_size: 0
    test_nms_cfg:
      nms_pre: 6000
      nms_post: 1000
      nms_thr: 0.7
      min_bbox_size: 0
  roi_head:
    _target_: src.models.heads.RoIHead
    roi_size: 14
    in_channels: 1024
    num_classes: 21
    use_roi_align: true
    feature_extractor:
      _target_: src.models.heads.roi_head.roi_feature_extractor
      arch: resnet50
      pretrained: true
    roi_target_generator:
      _target_: src.models.generators.RoITargetGenerator
      num_samples: 256
      fg_fraction: 0.25
      positive_iou_thr: 0.5
      negative_iou_thr_low: 0.0
      negative_iou_thr_high: 0.5
      use_gt: true
    bbox_deltas_normalize_means: [0, 0, 0, 0]
    bbox_deltas_normalize_stds: [0.1, 0.1, 0.2, 0.2]
    test_nms_cfg:
      nms_thr: 0.7
      score_thr: 0.01
